### ISSUE TITLE
crashes when almost any new mod added to modpack

### ISSUE THREAD

**Issue by camh98** [Globox1997/VillagerQuests#13]
I added this to my modpack, but it always causes old and newly created worlds to crash as they open.  It works perfectly fine on its own (successfully added quest datapacks), but as soon as I add certain mods (Adorn, Origins, and more possibly) it crashes.  I slowly have been testing the compatibility between each mod, but there does not seem to be consistency; I'll add one that crashes it, delete that mod, but then it continually crashes until I make an entire new minecraft file. I attached a crash report in case that helps.  I'm using 1.18

crash-2022-02-01_23.38.48-client.txt

**Comment by Globox1997** [comment]
The crash log isn't attached, please upload it again :)

**Comment by camh98** [comment]
[crash-2022-02-01_23.38.48-client.txt](https://github.com/Globox1997/VillagerQuests/files/7989002/crash-2022-02-01_23.38.48-client.txt)

**Comment by camh98** [comment]
Ok, after a bit more testing different mod combos for compatibility, I found that the ones that caused crashes when paired with VillagerQuests are the Illuminations mod and Origins/Origins Classes.  Everything else in the modpack seems to be compatible.

**Comment by Globox1997** [comment]
Should be fixed with the latest update

**Comment by Globox1997** [comment]
Reopen if still existent
