### ISSUE TITLE
Crashing on World Load 1.18

### ISSUE THREAD

**Issue by Gamerbolts** [Globox1997/VillagerQuests#14]
Hello I am creating a rather large modpack and when I add your mod and go to create a world it crashes Minecraft. What is weird is I have the mod to prevent crashing to desktop and it crashes to desktop here is the crash log and latest log. Any help is appreciated! Thank you!

[crash-2022-02-05_12.17.29-client.txt](https://github.com/Globox1997/VillagerQuests/files/8008593/crash-2022-02-05_12.17.29-client.txt)

[latest.log](https://github.com/Globox1997/VillagerQuests/files/8008595/latest.log)

**Comment by Globox1997** [comment]
Hopefully fixed with the latest update
