### ISSUE TITLE
Question: Unique ID for quests within datapack or across *all* datapacks? Also, integer only?

### ISSUE THREAD

**Issue by malagrond** [Globox1997/VillagerQuests#15]
So, I was wondering two things:

1) Does the ID need to only be unique within the datapack, or do I need to be concerned about multiple quest datapacks being loaded at the same time and possibly conflicting with the other pack's IDs?
and related to that:

~~2) What characters are allowed for an ID? Are they strings or integers? For example, could I make an ID something like "packname_fish1"?~~
Realized they're not in quotes, so they're integers. My bad on that one.

**Comment by malagrond** [comment]
Another question, actually: is it possible to flag a quest as available to all professions?

**Comment by Globox1997** [comment]
The quest id has to be unique to all datapacks.
the second question can be a feature request :)

**Comment by malagrond** [comment]
Cool, thanks!
