### ISSUE TITLE
hey i crashed when i clicked the quest scroll in the villager menu

### ISSUE THREAD

**Issue by gamingoninsulin** [Globox1997/VillagerQuests#18]
hey i chrashed when i clicked the villager notting happens it go as normal but then i clicked the qest scroll on the right (rei is overlapping btw)
and it chrashsedto desktop i have not enhough crashers on so i put it here the crashlog i am atatching it

[crash-2022-04-15_21.58.55-client.txt](https://github.com/Globox1997/VillagerQuests/files/8498051/crash-2022-04-15_21.58.55-client.txt)

it even crashing when i hide rei overlay just checked for sure

the version i use are 1.0.3 VillagerQuests, Fabric loader 0.13.3 and Fabric API 0.50.0+1.18.2

somting to do with Index 0 out of bounds for length 0
dont know what taht means

**Comment by gamingoninsulin** [comment]
oh and here is the datapack with that specific quest

[VillagerQuestsDatapack-0.1.0.zip](https://github.com/Globox1997/VillagerQuests/files/8498068/VillagerQuestsDatapack-0.1.0.zip)

it may i did a boo boo but json linter says everting is okay

this is what i found in the lates log
[latest.log](https://github.com/Globox1997/VillagerQuests/files/8498176/latest.log)

**Comment by gamingoninsulin** [comment]
god darn it i found it i had in the reward {} <- these suckers i needed [] <- this ill close it now ;)

**Comment by Globox1997** [comment]
Hi, great that you found the issue :)
