### ISSUE TITLE
using datapack entry results in no quest.

### ISSUE THREAD

**Issue by Monster-Zer0** [Globox1997/VillagerQuests#2]
I could be doing something wrong here.. but even using the example json.. modifying it.. or changing it in any way I can (like the id number.. etc) yields no new quest for the toolsmith. 

my folder layout is

data > villagerquests > quests > test_quest.json

im no newb at datapacks.. but also.. you know how working with code works.. sometimes you miss something.

thanks for the help.

**Comment by Globox1997** [comment]
Probably some small bug which I fixed - if you have less quests in your pack there is a high chance that the vill doesn't get any quests for the player
Waiting for #1 for approval until I publish a new version

**Comment by Monster-Zer0** [comment]
so you are saying that just because a quest is made in the datapack.. it's not a guarantee that a villager will have it. there is a chance?

**Comment by Monster-Zer0** [comment]
figured out the issue. appears it was a combo of not having a high enough level in your mod.. levelz.. and chance.

**Comment by Monster-Zer0** [comment]
actually upon further testing. quests show up when you spawn a villager in and have then take their profession.

however.. if a villager spawns from a modded structure.. like a village, then either takes on a profession or you can give them one.. and the quest will not show up.

in my testing. this is with a repurposed structure village.

**Comment by Globox1997** [comment]
I will look into it

**Comment by frikinjay** [comment]
The datapack doesnt seem to work?

**Comment by Monster-Zer0** [comment]
It works. You just have to spawn in a villager. You can't use one that naturally spawns in.

**Comment by Globox1997** [comment]
Released a new version, probably fixes the issue

**Comment by Monster-Zer0** [comment]
same issue, unfortunately.

**Comment by frikinjay** [comment]
I see the quests now but the icons are messed up and render way off from where theyre supposed to

**Comment by frikinjay** [comment]
And seems like /quest remove <player> remove or /quest remove <player> removeAll dont seem to do anything. I still cant see the quest i denied.

**Comment by wolfkidsounds** [comment]
> actually upon further testing. quests show up when you spawn a villager in and have then take their profession.
> 
> however.. if a villager spawns from a modded structure.. like a village, then either takes on a profession or you can give them one.. and the quest will not show up.
> 
> in my testing. this is with a repurposed structure village.

I'm having the same issue right now. However, would test further and report back.

---

When this type of villager (in my case armorer) is leveling up, everything behaves as normal. - However the initial quests (level 0) will not show up on villagers that where already spawned in before.

**Comment by Globox1997** [comment]
Quests which are finished by the player won't show up anymore (if no timer or timer is on going) on all villagers which have the same quest

**Comment by ghost** [comment]
can you send me your datapack because i cant get mine to work and id need one working to learn from it

**Comment by Globox1997** [comment]
Will close this issue by directing to my discord which can be found on the curseforge website.
If you have questions for how to create a datapack, pls ask there :)
