### ISSUE TITLE
Quests with tags

### ISSUE THREAD

**Issue by TheCompWiz** [Globox1997/VillagerQuests#20]
Is it possible to offer quests to players based on a tag assigned to them... and as part of the reward process... assign a tag to them?  so you could make layered quests.  i.e. finish quest A... assign tag "quest_complete_A" ... the next time they return... it checks the player and then offers quest B... etc...

**Comment by Globox1997** [comment]
This isn't possible with this mod. I decided to have a more additionally way for quests instead of being able to have a quest line.
