### ISSUE TITLE
Deprecated REI methods - Client and Server Crash 

### ISSUE THREAD

**Issue by Mattabase** [Globox1997/VillagerQuests#22]
![image](https://user-images.githubusercontent.com/2126947/173464709-db4c7b5a-798a-413f-acd6-ce9d5d7debf0.png)

Same issue causes a crash on Dedicated server start

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/VillagerQuests/commit/8f47d3d6699e3d5ff25fa4257763d57f4d6b8799](https://github.com/Globox1997/VillagerQuests/commit/8f47d3d6699e3d5ff25fa4257763d57f4d6b8799)
