### ISSUE TITLE
Quest not showing up in Modpack

### ISSUE THREAD

**Issue by Elska85** [Globox1997/VillagerQuests#25]
Hello so here is what is happening and why I think it might be happening. 

Quests do not show up on any villagers or wandering traders.

Mods that may conflict in modpack: Charm, moreVillagers, numismatic-overhaul

I think that one of these mods by adding new villagers/villages or the new currency system are interfering with the ability for villagers to distribute quests.

(Also nameplate mod is acting funky again just in general)

**Comment by Elska85** [comment]
Is there maybe a certain way to pull villagers from a mod such as the [more villager mod](https://www.curseforge.com/minecraft/mc-mods/more-villagers) or Charm mod

**Comment by Elska85** [comment]
It was just an issue I managed to solve by reordering some things in the config folder.

**Comment by Globox1997** [comment]
Sounds odd to me but what do you mean with nameplate?

**Comment by Elska85** [comment]
> Sounds odd to me but what do you mean with nameplate?

Don't worry about it, you addressed that issue already in the [nameplate mod](https://www.curseforge.com/minecraft/mc-mods/nameplate). It was just that issue where the custom entities would be reset every time you started minecraft in 1.18.2 version.
