### ISSUE TITLE
Quest rewards and tributes are tied to scroll bar.

### ISSUE THREAD

**Issue by Elska85** [Globox1997/VillagerQuests#26]
Having issue where icons get misaligned because of scroll bar for quests.

![image](https://user-images.githubusercontent.com/85760736/184448427-c88fccef-7a24-4d5b-9bf6-a10e26f53306.png)

![image](https://user-images.githubusercontent.com/85760736/184448518-f1a5a3fa-fc41-4595-a009-92683235ae3c.png)

**Comment by Elska85** [comment]
Also this is 1.18.2 version. Would be nice if their was separate scroll wheel for right side.
![image](https://user-images.githubusercontent.com/85760736/184448810-c2e27901-7680-44e6-bd4a-4e4322b506c0.png)

**Comment by Elska85** [comment]
Here is snip of last example photos code in data pack.
![image](https://user-images.githubusercontent.com/85760736/184701941-a4974d57-7d13-4c46-9436-7b57063909ef.png)

**Comment by Globox1997** [comment]
Thanks for reporting, fixed with [https://github.com/Globox1997/VillagerQuests/commit/f42ed4108ef0a230c4a846e7e9a367f5a28f00af](https://github.com/Globox1997/VillagerQuests/commit/f42ed4108ef0a230c4a846e7e9a367f5a28f00af)
You didn't read this section [https://github.com/Globox1997/VillagerQuests#limitations](https://github.com/Globox1997/VillagerQuests#limitations)

**Comment by Elska85** [comment]
> Thanks for reporting, fixed with [f42ed41](https://github.com/Globox1997/VillagerQuests/commit/f42ed4108ef0a230c4a846e7e9a367f5a28f00af) You didn't read this section https://github.com/Globox1997/VillagerQuests#limitations

I understand, I'm just saying it would greatly improve the Quality of Life for your users if an additional scroll bar or something was added to the right side with the ability to format quests. Just a suggestion I guess that would allow users to add more role play and loot to their game. I understand that you are very busy and I'm just appreciative while the mod works as well as it does. I just personally won't be using it for my modpack or server for a while because of the limitations as of right now. 

Keep up the great work Globox. I wish you the best of success. Thank you for all the awesome content you've made so far and can't wait to see where you go next.
