### ISSUE TITLE
crash when attempting to look at active quests

### ISSUE THREAD

**Issue by Monster-Zer0** [Globox1997/VillagerQuests#4]
https://paste.alloffabric.com/kimesekuqo.http

after accepting a quest.. then looking at my quests.. I get this error

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/VillagerQuests/commit/7bfe4f4521edff735d2dc4642ca69aef6376506e](https://github.com/Globox1997/VillagerQuests/commit/7bfe4f4521edff735d2dc4642ca69aef6376506e)
