### ISSUE TITLE
Any way to add villager quest datapacks to ATLauncher?

### ISSUE THREAD

**Issue by TheAritiam** [Globox1997/VillagerQuests#41]
I've read the required path for any datapacks for new quests but I use ATLauncher for my mods and I'm wondering if there was any way of adding datapacks through there or if I have to go somewhere else to use VillagerQuest effectively.

ATLauncher has a data folder in both the Instance and the saves folders, though both didn't have the villagerquest folder in them and the datapacks folder in the folder of whatever world I have in saves doesn't have the folder either.

**Comment by Globox1997** [comment]
Mh may ask Ray at the globox discord
