### ISSUE TITLE
Trades are disabled by default

### ISSUE THREAD

**Issue by Sparkyberry** [Globox1997/VillagerQuests#43]
### Minecraft Version

1.20.x

### Mod Loader Version

Fabric 0.15.1

### Mod Version

villagerquests-1.1.0.jar

### Describe the Issue

Hello ! 
The issue is that the trade option is disabled by default for villagers, even those appearing naturally in villages. We have to activate it manually for all villagers you meet.

### latest.log

[latest.log](https://github.com/Globox1997/VillagerQuests/files/14055698/latest.log)

### Do you use any other mods except the required ones?

No

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/VillagerQuests/commit/2cc1b1c498647b234e9ffee9fd59b9aad354f0d2](https://github.com/Globox1997/VillagerQuests/commit/2cc1b1c498647b234e9ffee9fd59b9aad354f0d2)
