### ISSUE TITLE
Error during Roughly Enough Items' initialization

### ISSUE THREAD

**Issue by KevzCz** [Globox1997/VillagerQuests#44]
### Minecraft Version

1.20.x

### Mod Loader Version

0.15.6

### Mod Version

1.1.0

### Describe the Issue

![image](https://github.com/Globox1997/VillagerQuests/assets/130611225/42219a43-396d-4b4c-abab-df19a2ee5f67)
Presumably an issue between REI and VillagerQuests

### latest.log

[latest.log](https://github.com/Globox1997/VillagerQuests/files/14071653/latest.log)

**Comment by Alvaro2003j** [comment]
I have that same error :c

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/VillagerQuests/commit/4e96beebc53644667fdb26af0186e9bf0503f379](https://github.com/Globox1997/VillagerQuests/commit/4e96beebc53644667fdb26af0186e9bf0503f379)
