### ISSUE TITLE
FTB Quests 2001.3.3 does not work with VillagerQuests

### ISSUE THREAD

**Issue by RockZe** [Globox1997/VillagerQuests#45]
### Minecraft Version

1.20.x

### Mod Loader Version

0.15.6

### Mod Version

villagerquests-1.1.1+1.20.1

### Describe the Issue

The latest version of FTB Quests does not work with villagerquests-1.1.1+1.20.1
![image](https://github.com/Globox1997/VillagerQuests/assets/123874691/509d4b45-30c3-4cc5-8af0-d9a49b0ae18f)

### latest.log

[latest.log](https://github.com/Globox1997/VillagerQuests/files/14228827/latest.log)

**Comment by Globox1997** [comment]
Yes this is due to an agreement with ftb.
For the sake of not getting github issues on ftb's side.

**Comment by RockZe** [comment]
> For the sake of not getting github issues on ftb's side.

Does this mean that it will not be possible to solve the problem with an update in the future, since there are problems on the part of ftb?

**Comment by Globox1997** [comment]
No there are no problems on the part of ftb, I just have to update when they do but I am not updating that often.
Working on an update rn tho :)
