### ISSUE TITLE
The ability to turn off the voice acting of the villager

### ISSUE THREAD

**Issue by RockZe** [Globox1997/VillagerQuests#46]
### Make sure you are not opening a duplicate.

- [x] I have searched the issue tracker and did not find an issue describing my bug.

### Description of your suggestion.

I don't know how to explain it in more detail, but it would be great to disable, for example, in the config, the voiceover from villagers.

The fact is that some mods use a different voice acting, for example in MCA, so if it is possible to disable this voice acting or make a voice acting of your choice, then it will be just fine!

**Comment by Globox1997** [comment]
Added a config option with [https://github.com/Globox1997/VillagerQuests/commits/1.21-ftb/](https://github.com/Globox1997/VillagerQuests/commits/1.21-ftb/)
