### ISSUE TITLE
Compatibility issue with Numismatic Overhaul

### ISSUE THREAD

**Issue by RockZe** [Globox1997/VillagerQuests#48]
### Minecraft Version

1.20.x

### Mod Loader Version

0.15.6

### Mod Version

villagerquests-1.1.1+1.20.1

### Describe the Issue

When opening a store from the Numismatic Overhaul mod, a crash occurs from the server

### latest.log

[crash-2024-03-26_22.03.15-client.txt](https://github.com/Globox1997/VillagerQuests/files/14763629/crash-2024-03-26_22.03.15-client.txt)

### Do you use any other mods except the required ones?

Numismatic Overhaul

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/VillagerQuests/commit/3f436b89faf41fa49fcb0f82f8f5f97953fec9ff](https://github.com/Globox1997/VillagerQuests/commit/3f436b89faf41fa49fcb0f82f8f5f97953fec9ff)
