### ISSUE TITLE
Unable to get this mod the function. Please give me some guidance.  

### ISSUE THREAD

**Issue by alarmgoose** [Globox1997/VillagerQuests#49]
I can't seem to get this mod to work. I created a datapack, even used the example datapack. I'm also not a newbie with datapacks so I'm pretty sure the set up is correct. The quest never show up. I've started a new game, located different villages, with no luck. I even downloaded other modpacks that use this mod to see how they got it to work, only to discover that out of the twenty packs I downloaded, none of them actually uses the mod. They just have it in their modpacks without using it.  Are there any modpacks that actually make use of this mod, and if so, could someone please point me in that direction?

**Comment by alarmgoose** [comment]
Anybody? It's been almost two months.  Is this mod still active?

**Comment by Globox1997** [comment]
Which version do you use?

**Comment by alarmgoose** [comment]
> Which version do you use?

I didn't think anyone was ever going to reply. I just happen to finally check back to see this. I'm using ftb-quests-forge-2001.4.4. I was finally able to link a villager with the UUID in Ftbquest but no actual quest appear when talking to the villager who is a farmer. The UUID is 15F2F9F5-8080-6E3D-BF3B-58B407391E30. I have a datapack with the quest in as well. I want this to work badly. Is there anyone who actually got it to work and has a modpack with it installed and functioning?

**Comment by Globox1997** [comment]
This mod is only for prebuild maps where you have to manually set up quests for villagers.

**Comment by alarmgoose** [comment]
> This mod is only for prebuild maps where you have to manually set up quests for villagers.

Oh I had no idea. Was that mention anywhere in the description.

**Comment by Globox1997** [comment]
Seems like you never read the description.
