### ISSUE TITLE
All the icons on the quest screen render way off from where theyre supposed to.

### ISSUE THREAD

**Issue by frikinjay** [Globox1997/VillagerQuests#5]
All the icons on the quest screen render way off from where theyre supposed to. And the icons on the left dont even render. 

![image](https://user-images.githubusercontent.com/88995340/138252581-307b2627-dc8f-4698-9c29-93654a8ca3ed.png)

**Comment by Globox1997** [comment]
Does this happen when the mod is only installed?

**Comment by Globox1997** [comment]
And how can I recreate this :D

**Comment by frikinjay** [comment]
I have not tried it with just the mod, and the way to recreate is just put in a quest and check it.

**Comment by Elska85** [comment]
Similar issue. Seems the item icons are tied with the scroll bard on left. I also think there should be a scroll bar on right for longer quest descriptions. This seems to be a reoccurring issue in the 1.18.2 version.

![capture3](https://user-images.githubusercontent.com/85760736/184698495-6fef2aaf-114b-4a63-b0de-9103674d9c05.JPG)
![image](https://user-images.githubusercontent.com/85760736/184698729-a381fe64-7ba5-44d3-8bb3-51e74b77af8b.png)

**Comment by Elska85** [comment]
> And how can I recreate this :D

Similar issue. Seems the item icons are tied with the scroll bard on left. I also think there should be a scroll bar on right for longer quest descriptions. This seems to be a reoccurring issue in the 1.18.2 version. I also just added an example of what similar text looks like causing that overlap. Also the return to trade bar is overlapped by REI, but quest is fine. THink the two should be tied together in config folder.

keep in mind I also have charm and more villagers installed in this modpack.

![capture3](https://user-images.githubusercontent.com/85760736/184698495-6fef2aaf-114b-4a63-b0de-9103674d9c05.JPG)

lines up fine if you don't touch the slider.
![capture2](https://user-images.githubusercontent.com/85760736/184699146-d66d4d48-52b3-47f3-bf67-9146ace4b550.JPG)

example of what overlap description looks like.
![image](https://user-images.githubusercontent.com/85760736/184698729-a381fe64-7ba5-44d3-8bb3-51e74b77af8b.png)

**Comment by Globox1997** [comment]
Fixed it with the latest update
