### ISSUE TITLE
Trader name is treated wrong

### ISSUE THREAD

**Issue by MJRamon** [Globox1997/VillagerQuests#9]
When villager with a namespace is used, his name becomes "Namespace:profession", but instead it must be proper language name.
"Фермер", not "Farmer", if Russian language is used.
![2021-12-29_07 57 56](https://user-images.githubusercontent.com/2642227/147631959-4061e963-5df2-4058-9ae7-5cb67ce74e77.png)

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/VillagerQuests/commit/dc42f94d4716383be2bff46e2ae0c3efb139b6c0](https://github.com/Globox1997/VillagerQuests/commit/dc42f94d4716383be2bff46e2ae0c3efb139b6c0)
